export interface DappProps {
  name: string
  author: string
  hash: string
  sign: string
  size: number
  version: string
  logo: string
  pathStorage: string
  createTime: number
  bundleId: string
  orientation: string
  isFullScreen: number
  statusBar: string
  groupId: number
  page: number
  position: {
    x: number
    y: number
    width: number
    height: number
  }
  abiData: any[]
  binData: string
  constructorData: string
  type: number
  url: string
  urlScript: string
  parent: string
  profileId: number
  isDefault: number
  isHidden: number
  isLocked: number
  lastTimeOpen: number
  lastTimeModified: number
  scriptStr: string
  isAutoScript: number
  isFavorite: number
  urlPack: string
  isUserApp: number
  notificationEnabled: number
  lockScreenNotificationEnabled: number
  canShowBadge: number
  popupNotificationEnabled: number
  silentUntilTime: number
  isIncludeOnly: number
  include: string[]
  exclude: string[]
  isTaskbar: number
  category: string
  isVisibleOnHome: number
}
